// TSL inference gRPC contract between the Golang backend gateway and the
// Python AI inference service (bidirectional streaming — no HTTP fallback,
// per root DOX). Source of truth lives here in docs/api/; generated stubs:
//   Go:     Backend/internal/pb/
//   Python: Inference_backend/inference/pb/
// Regeneration commands are documented in Backend/AGENTS.md and
// Inference_backend/AGENTS.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: tsl_inference.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TslInference_StreamInference_FullMethodName = "/signmind.inference.v1.TslInference/StreamInference"
	TslInference_UploadModel_FullMethodName     = "/signmind.inference.v1.TslInference/UploadModel"
	TslInference_StreamLogs_FullMethodName      = "/signmind.inference.v1.TslInference/StreamLogs"
	TslInference_GetTuning_FullMethodName       = "/signmind.inference.v1.TslInference/GetTuning"
	TslInference_SetTuning_FullMethodName       = "/signmind.inference.v1.TslInference/SetTuning"
)

// TslInferenceClient is the client API for TslInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TslInferenceClient interface {
	// Client (backend) streams landmark frames; server (Python) streams
	// predictions whenever its 30-frame sliding window is full.
	StreamInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LandmarkFrame, Prediction], error)
	// Atomically replace the LSTM model and its companion files. The client
	// streams, per file, one FileHeader followed by that file's chunks; the
	// model file and label map are both required in a single call (preprocess
	// config optional). The server validates the staged files (interpreter
	// loads, label map parses) before hot-swapping; on any failure the
	// previously loaded model stays live and the RPC returns an error status.
	UploadModel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadModelRequest, UploadModelResponse], error)
	// Server streams its log records to the gateway: first up to
	// `history_lines` buffered entries, then live entries until the client
	// cancels.
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Read / adjust runtime inference tuning (thresholds). SetTuning applies
	// only the fields present in the request and returns the full resulting
	// state. Values are runtime-only: they reset to preprocess_config.json
	// defaults on service restart.
	GetTuning(ctx context.Context, in *GetTuningRequest, opts ...grpc.CallOption) (*TuningState, error)
	SetTuning(ctx context.Context, in *SetTuningRequest, opts ...grpc.CallOption) (*TuningState, error)
}

type tslInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewTslInferenceClient(cc grpc.ClientConnInterface) TslInferenceClient {
	return &tslInferenceClient{cc}
}

func (c *tslInferenceClient) StreamInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LandmarkFrame, Prediction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TslInference_ServiceDesc.Streams[0], TslInference_StreamInference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LandmarkFrame, Prediction]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TslInference_StreamInferenceClient = grpc.BidiStreamingClient[LandmarkFrame, Prediction]

func (c *tslInferenceClient) UploadModel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadModelRequest, UploadModelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TslInference_ServiceDesc.Streams[1], TslInference_UploadModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadModelRequest, UploadModelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TslInference_UploadModelClient = grpc.ClientStreamingClient[UploadModelRequest, UploadModelResponse]

func (c *tslInferenceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TslInference_ServiceDesc.Streams[2], TslInference_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TslInference_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *tslInferenceClient) GetTuning(ctx context.Context, in *GetTuningRequest, opts ...grpc.CallOption) (*TuningState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TuningState)
	err := c.cc.Invoke(ctx, TslInference_GetTuning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tslInferenceClient) SetTuning(ctx context.Context, in *SetTuningRequest, opts ...grpc.CallOption) (*TuningState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TuningState)
	err := c.cc.Invoke(ctx, TslInference_SetTuning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TslInferenceServer is the server API for TslInference service.
// All implementations must embed UnimplementedTslInferenceServer
// for forward compatibility.
type TslInferenceServer interface {
	// Client (backend) streams landmark frames; server (Python) streams
	// predictions whenever its 30-frame sliding window is full.
	StreamInference(grpc.BidiStreamingServer[LandmarkFrame, Prediction]) error
	// Atomically replace the LSTM model and its companion files. The client
	// streams, per file, one FileHeader followed by that file's chunks; the
	// model file and label map are both required in a single call (preprocess
	// config optional). The server validates the staged files (interpreter
	// loads, label map parses) before hot-swapping; on any failure the
	// previously loaded model stays live and the RPC returns an error status.
	UploadModel(grpc.ClientStreamingServer[UploadModelRequest, UploadModelResponse]) error
	// Server streams its log records to the gateway: first up to
	// `history_lines` buffered entries, then live entries until the client
	// cancels.
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// Read / adjust runtime inference tuning (thresholds). SetTuning applies
	// only the fields present in the request and returns the full resulting
	// state. Values are runtime-only: they reset to preprocess_config.json
	// defaults on service restart.
	GetTuning(context.Context, *GetTuningRequest) (*TuningState, error)
	SetTuning(context.Context, *SetTuningRequest) (*TuningState, error)
	mustEmbedUnimplementedTslInferenceServer()
}

// UnimplementedTslInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTslInferenceServer struct{}

func (UnimplementedTslInferenceServer) StreamInference(grpc.BidiStreamingServer[LandmarkFrame, Prediction]) error {
	return status.Error(codes.Unimplemented, "method StreamInference not implemented")
}
func (UnimplementedTslInferenceServer) UploadModel(grpc.ClientStreamingServer[UploadModelRequest, UploadModelResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadModel not implemented")
}
func (UnimplementedTslInferenceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedTslInferenceServer) GetTuning(context.Context, *GetTuningRequest) (*TuningState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTuning not implemented")
}
func (UnimplementedTslInferenceServer) SetTuning(context.Context, *SetTuningRequest) (*TuningState, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTuning not implemented")
}
func (UnimplementedTslInferenceServer) mustEmbedUnimplementedTslInferenceServer() {}
func (UnimplementedTslInferenceServer) testEmbeddedByValue()                      {}

// UnsafeTslInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TslInferenceServer will
// result in compilation errors.
type UnsafeTslInferenceServer interface {
	mustEmbedUnimplementedTslInferenceServer()
}

func RegisterTslInferenceServer(s grpc.ServiceRegistrar, srv TslInferenceServer) {
	// If the following call panics, it indicates UnimplementedTslInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TslInference_ServiceDesc, srv)
}

func _TslInference_StreamInference_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TslInferenceServer).StreamInference(&grpc.GenericServerStream[LandmarkFrame, Prediction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TslInference_StreamInferenceServer = grpc.BidiStreamingServer[LandmarkFrame, Prediction]

func _TslInference_UploadModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TslInferenceServer).UploadModel(&grpc.GenericServerStream[UploadModelRequest, UploadModelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TslInference_UploadModelServer = grpc.ClientStreamingServer[UploadModelRequest, UploadModelResponse]

func _TslInference_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TslInferenceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TslInference_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _TslInference_GetTuning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTuningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TslInferenceServer).GetTuning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TslInference_GetTuning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TslInferenceServer).GetTuning(ctx, req.(*GetTuningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TslInference_SetTuning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTuningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TslInferenceServer).SetTuning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TslInference_SetTuning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TslInferenceServer).SetTuning(ctx, req.(*SetTuningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TslInference_ServiceDesc is the grpc.ServiceDesc for TslInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TslInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signmind.inference.v1.TslInference",
	HandlerType: (*TslInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTuning",
			Handler:    _TslInference_GetTuning_Handler,
		},
		{
			MethodName: "SetTuning",
			Handler:    _TslInference_SetTuning_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInference",
			Handler:       _TslInference_StreamInference_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadModel",
			Handler:       _TslInference_UploadModel_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _TslInference_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tsl_inference.proto",
}
