// TSL inference gRPC contract between the Golang backend gateway and the
// Python AI inference service (bidirectional streaming — no HTTP fallback,
// per root DOX). Source of truth lives here in docs/api/; generated stubs:
//   Go:     Backend/internal/pb/
//   Python: Inference_backend/inference/pb/
// Regeneration commands are documented in Backend/AGENTS.md and
// Inference_backend/AGENTS.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: tsl_inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileKind int32

const (
	FileKind_FILE_KIND_UNSPECIFIED FileKind = 0
	// The LSTM .tflite flatbuffer (required).
	FileKind_FILE_KIND_TFLITE_MODEL FileKind = 1
	// label_map.json: {"label": index, ...} (required).
	FileKind_FILE_KIND_LABEL_MAP FileKind = 2
	// preprocess_config.json saved by training (optional).
	FileKind_FILE_KIND_PREPROCESS_CONFIG FileKind = 3
)

// Enum value maps for FileKind.
var (
	FileKind_name = map[int32]string{
		0: "FILE_KIND_UNSPECIFIED",
		1: "FILE_KIND_TFLITE_MODEL",
		2: "FILE_KIND_LABEL_MAP",
		3: "FILE_KIND_PREPROCESS_CONFIG",
	}
	FileKind_value = map[string]int32{
		"FILE_KIND_UNSPECIFIED":       0,
		"FILE_KIND_TFLITE_MODEL":      1,
		"FILE_KIND_LABEL_MAP":         2,
		"FILE_KIND_PREPROCESS_CONFIG": 3,
	}
)

func (x FileKind) Enum() *FileKind {
	p := new(FileKind)
	*p = x
	return p
}

func (x FileKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tsl_inference_proto_enumTypes[0].Descriptor()
}

func (FileKind) Type() protoreflect.EnumType {
	return &file_tsl_inference_proto_enumTypes[0]
}

func (x FileKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileKind.Descriptor instead.
func (FileKind) EnumDescriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{0}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARNING",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARNING":     3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_tsl_inference_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_tsl_inference_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{1}
}

type LandmarkFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic per-connection frame counter (mirrors the WS `seq`).
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Client capture time, Unix epoch milliseconds.
	TimestampMs int64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// 441 floats per the root Feature Vector Spec (Agents.md). The service
	// consumes the position block (first 147) and recomputes deltas after
	// person-invariant normalization, mirroring training.
	Features []float32 `protobuf:"fixed32,3,rep,packed,name=features,proto3" json:"features,omitempty"`
	// True to clear the server-side sliding window; `features` may be empty.
	Reset_        bool `protobuf:"varint,4,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandmarkFrame) Reset() {
	*x = LandmarkFrame{}
	mi := &file_tsl_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandmarkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandmarkFrame) ProtoMessage() {}

func (x *LandmarkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandmarkFrame.ProtoReflect.Descriptor instead.
func (*LandmarkFrame) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{0}
}

func (x *LandmarkFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LandmarkFrame) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LandmarkFrame) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *LandmarkFrame) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type Prediction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `seq` of the newest frame included in the window.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Top-1 label from label_map.json; empty when is_uncertain.
	Word string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	// Top-1 softmax probability.
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Idle/no-hands bypass fired (no model invocation).
	IsIdle bool `protobuf:"varint,4,opt,name=is_idle,json=isIdle,proto3" json:"is_idle,omitempty"`
	// Top-1 below the trained confidence threshold.
	IsUncertain bool `protobuf:"varint,5,opt,name=is_uncertain,json=isUncertain,proto3" json:"is_uncertain,omitempty"`
	// Up to 5 entries, descending probability, prob > 0.01. When the service
	// runs with debug_mode on (TuningState), this expands to up to 10 entries
	// with no probability cutoff, for webui analysis.
	Top []*ClassProb `protobuf:"bytes,6,rep,name=top,proto3" json:"top,omitempty"`
	// Inference wall time in microseconds.
	InferenceMicros int64 `protobuf:"varint,7,opt,name=inference_micros,json=inferenceMicros,proto3" json:"inference_micros,omitempty"`
	// Probability mass not covered by `top` (the "other" bucket). Only
	// populated when debug_mode is on; 0 otherwise.
	OtherProb     float32 `protobuf:"fixed32,8,opt,name=other_prob,json=otherProb,proto3" json:"other_prob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_tsl_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Prediction) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Prediction) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Prediction) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Prediction) GetIsIdle() bool {
	if x != nil {
		return x.IsIdle
	}
	return false
}

func (x *Prediction) GetIsUncertain() bool {
	if x != nil {
		return x.IsUncertain
	}
	return false
}

func (x *Prediction) GetTop() []*ClassProb {
	if x != nil {
		return x.Top
	}
	return nil
}

func (x *Prediction) GetInferenceMicros() int64 {
	if x != nil {
		return x.InferenceMicros
	}
	return 0
}

func (x *Prediction) GetOtherProb() float32 {
	if x != nil {
		return x.OtherProb
	}
	return 0
}

type ClassProb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Prob          float32                `protobuf:"fixed32,2,opt,name=prob,proto3" json:"prob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassProb) Reset() {
	*x = ClassProb{}
	mi := &file_tsl_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassProb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassProb) ProtoMessage() {}

func (x *ClassProb) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassProb.ProtoReflect.Descriptor instead.
func (*ClassProb) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ClassProb) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassProb) GetProb() float32 {
	if x != nil {
		return x.Prob
	}
	return 0
}

type FileHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  FileKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=signmind.inference.v1.FileKind" json:"kind,omitempty"`
	// Original filename, informational only; the server picks storage names.
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// Total file size in bytes; the server rejects mismatched uploads.
	SizeBytes     uint64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHeader) Reset() {
	*x = FileHeader{}
	mi := &file_tsl_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHeader) ProtoMessage() {}

func (x *FileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHeader.ProtoReflect.Descriptor instead.
func (*FileHeader) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{3}
}

func (x *FileHeader) GetKind() FileKind {
	if x != nil {
		return x.Kind
	}
	return FileKind_FILE_KIND_UNSPECIFIED
}

func (x *FileHeader) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileHeader) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type UploadModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadModelRequest_Header
	//	*UploadModelRequest_Chunk
	Payload       isUploadModelRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadModelRequest) Reset() {
	*x = UploadModelRequest{}
	mi := &file_tsl_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelRequest) ProtoMessage() {}

func (x *UploadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelRequest.ProtoReflect.Descriptor instead.
func (*UploadModelRequest) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{4}
}

func (x *UploadModelRequest) GetPayload() isUploadModelRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadModelRequest) GetHeader() *FileHeader {
	if x != nil {
		if x, ok := x.Payload.(*UploadModelRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *UploadModelRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadModelRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadModelRequest_Payload interface {
	isUploadModelRequest_Payload()
}

type UploadModelRequest_Header struct {
	// Starts a new file; must precede that file's chunks.
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type UploadModelRequest_Chunk struct {
	// Next chunk of the current file (suggested <= 1 MiB per message).
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadModelRequest_Header) isUploadModelRequest_Payload() {}

func (*UploadModelRequest_Chunk) isUploadModelRequest_Payload() {}

type UploadModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the new model is live (always true on OK status).
	Reloaded bool `protobuf:"varint,1,opt,name=reloaded,proto3" json:"reloaded,omitempty"`
	// Number of classes in the uploaded label map.
	NumClasses uint32 `protobuf:"varint,2,opt,name=num_classes,json=numClasses,proto3" json:"num_classes,omitempty"`
	// Model input window length (frames), read from the interpreter.
	SequenceLen uint32 `protobuf:"varint,3,opt,name=sequence_len,json=sequenceLen,proto3" json:"sequence_len,omitempty"`
	// Model input feature dimension, read from the interpreter.
	FeatureDim    uint32 `protobuf:"varint,4,opt,name=feature_dim,json=featureDim,proto3" json:"feature_dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadModelResponse) Reset() {
	*x = UploadModelResponse{}
	mi := &file_tsl_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelResponse) ProtoMessage() {}

func (x *UploadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelResponse.ProtoReflect.Descriptor instead.
func (*UploadModelResponse) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{5}
}

func (x *UploadModelResponse) GetReloaded() bool {
	if x != nil {
		return x.Reloaded
	}
	return false
}

func (x *UploadModelResponse) GetNumClasses() uint32 {
	if x != nil {
		return x.NumClasses
	}
	return 0
}

func (x *UploadModelResponse) GetSequenceLen() uint32 {
	if x != nil {
		return x.SequenceLen
	}
	return 0
}

func (x *UploadModelResponse) GetFeatureDim() uint32 {
	if x != nil {
		return x.FeatureDim
	}
	return 0
}

type StreamLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum level to receive; UNSPECIFIED means INFO.
	MinLevel LogLevel `protobuf:"varint,1,opt,name=min_level,json=minLevel,proto3,enum=signmind.inference.v1.LogLevel" json:"min_level,omitempty"`
	// How many buffered past entries to replay before live entries (0 = none;
	// capped by the server-side ring buffer size).
	HistoryLines  uint32 `protobuf:"varint,2,opt,name=history_lines,json=historyLines,proto3" json:"history_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_tsl_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{6}
}

func (x *StreamLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *StreamLogsRequest) GetHistoryLines() uint32 {
	if x != nil {
		return x.HistoryLines
	}
	return 0
}

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record time, Unix epoch milliseconds.
	TimestampMs int64    `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Level       LogLevel `protobuf:"varint,2,opt,name=level,proto3,enum=signmind.inference.v1.LogLevel" json:"level,omitempty"`
	// Python logger name (e.g. "inference.engine").
	Logger        string `protobuf:"bytes,3,opt,name=logger,proto3" json:"logger,omitempty"`
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_tsl_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetLogger() string {
	if x != nil {
		return x.Logger
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTuningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTuningRequest) Reset() {
	*x = GetTuningRequest{}
	mi := &file_tsl_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTuningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTuningRequest) ProtoMessage() {}

func (x *GetTuningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTuningRequest.ProtoReflect.Descriptor instead.
func (*GetTuningRequest) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{8}
}

// All fields optional: only those present are applied.
type SetTuningRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reject predictions whose top-1 softmax is below this (0.0–1.0).
	ConfidenceThreshold *float32 `protobuf:"fixed32,1,opt,name=confidence_threshold,json=confidenceThreshold,proto3,oneof" json:"confidence_threshold,omitempty"`
	// Idle bypass: minimum frames (of the window) with any hand present.
	IdleMinFramesWithHands *uint32 `protobuf:"varint,2,opt,name=idle_min_frames_with_hands,json=idleMinFramesWithHands,proto3,oneof" json:"idle_min_frames_with_hands,omitempty"`
	// Idle bypass: mean per-coordinate std-dev below this counts as static.
	IdleMotionStdThreshold *float32 `protobuf:"fixed32,3,opt,name=idle_motion_std_threshold,json=idleMotionStdThreshold,proto3,oneof" json:"idle_motion_std_threshold,omitempty"`
	// Dev/debug mode: service logs at DEBUG level and Predictions carry the
	// full probability breakdown (expanded `top` + `other_prob`). Set by the
	// gateway from its ENV (Dev -> true); runtime-only like the other fields.
	DebugMode     *bool `protobuf:"varint,4,opt,name=debug_mode,json=debugMode,proto3,oneof" json:"debug_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTuningRequest) Reset() {
	*x = SetTuningRequest{}
	mi := &file_tsl_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTuningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTuningRequest) ProtoMessage() {}

func (x *SetTuningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTuningRequest.ProtoReflect.Descriptor instead.
func (*SetTuningRequest) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{9}
}

func (x *SetTuningRequest) GetConfidenceThreshold() float32 {
	if x != nil && x.ConfidenceThreshold != nil {
		return *x.ConfidenceThreshold
	}
	return 0
}

func (x *SetTuningRequest) GetIdleMinFramesWithHands() uint32 {
	if x != nil && x.IdleMinFramesWithHands != nil {
		return *x.IdleMinFramesWithHands
	}
	return 0
}

func (x *SetTuningRequest) GetIdleMotionStdThreshold() float32 {
	if x != nil && x.IdleMotionStdThreshold != nil {
		return *x.IdleMotionStdThreshold
	}
	return 0
}

func (x *SetTuningRequest) GetDebugMode() bool {
	if x != nil && x.DebugMode != nil {
		return *x.DebugMode
	}
	return false
}

type TuningState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConfidenceThreshold    float32                `protobuf:"fixed32,1,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	IdleMinFramesWithHands uint32                 `protobuf:"varint,2,opt,name=idle_min_frames_with_hands,json=idleMinFramesWithHands,proto3" json:"idle_min_frames_with_hands,omitempty"`
	IdleMotionStdThreshold float32                `protobuf:"fixed32,3,opt,name=idle_motion_std_threshold,json=idleMotionStdThreshold,proto3" json:"idle_motion_std_threshold,omitempty"`
	// Read-only facts about the loaded model, for webui display.
	ModelLoaded bool   `protobuf:"varint,4,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	NumClasses  uint32 `protobuf:"varint,5,opt,name=num_classes,json=numClasses,proto3" json:"num_classes,omitempty"`
	SequenceLen uint32 `protobuf:"varint,6,opt,name=sequence_len,json=sequenceLen,proto3" json:"sequence_len,omitempty"`
	FeatureDim  uint32 `protobuf:"varint,7,opt,name=feature_dim,json=featureDim,proto3" json:"feature_dim,omitempty"`
	// Current debug/Dev mode (see SetTuningRequest.debug_mode).
	DebugMode     bool `protobuf:"varint,8,opt,name=debug_mode,json=debugMode,proto3" json:"debug_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuningState) Reset() {
	*x = TuningState{}
	mi := &file_tsl_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningState) ProtoMessage() {}

func (x *TuningState) ProtoReflect() protoreflect.Message {
	mi := &file_tsl_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningState.ProtoReflect.Descriptor instead.
func (*TuningState) Descriptor() ([]byte, []int) {
	return file_tsl_inference_proto_rawDescGZIP(), []int{10}
}

func (x *TuningState) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

func (x *TuningState) GetIdleMinFramesWithHands() uint32 {
	if x != nil {
		return x.IdleMinFramesWithHands
	}
	return 0
}

func (x *TuningState) GetIdleMotionStdThreshold() float32 {
	if x != nil {
		return x.IdleMotionStdThreshold
	}
	return 0
}

func (x *TuningState) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *TuningState) GetNumClasses() uint32 {
	if x != nil {
		return x.NumClasses
	}
	return 0
}

func (x *TuningState) GetSequenceLen() uint32 {
	if x != nil {
		return x.SequenceLen
	}
	return 0
}

func (x *TuningState) GetFeatureDim() uint32 {
	if x != nil {
		return x.FeatureDim
	}
	return 0
}

func (x *TuningState) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

var File_tsl_inference_proto protoreflect.FileDescriptor

const file_tsl_inference_proto_rawDesc = "" +
	"\n" +
	"\x13tsl_inference.proto\x12\x15signmind.inference.v1\"v\n" +
	"\rLandmarkFrame\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\x02R\bfeatures\x12\x14\n" +
	"\x05reset\x18\x04 \x01(\bR\x05reset\"\x8c\x02\n" +
	"\n" +
	"Prediction\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x17\n" +
	"\ais_idle\x18\x04 \x01(\bR\x06isIdle\x12!\n" +
	"\fis_uncertain\x18\x05 \x01(\bR\visUncertain\x122\n" +
	"\x03top\x18\x06 \x03(\v2 .signmind.inference.v1.ClassProbR\x03top\x12)\n" +
	"\x10inference_micros\x18\a \x01(\x03R\x0finferenceMicros\x12\x1d\n" +
	"\n" +
	"other_prob\x18\b \x01(\x02R\totherProb\"5\n" +
	"\tClassProb\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04prob\x18\x02 \x01(\x02R\x04prob\"|\n" +
	"\n" +
	"FileHeader\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.signmind.inference.v1.FileKindR\x04kind\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"t\n" +
	"\x12UploadModelRequest\x12;\n" +
	"\x06header\x18\x01 \x01(\v2!.signmind.inference.v1.FileHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\x96\x01\n" +
	"\x13UploadModelResponse\x12\x1a\n" +
	"\breloaded\x18\x01 \x01(\bR\breloaded\x12\x1f\n" +
	"\vnum_classes\x18\x02 \x01(\rR\n" +
	"numClasses\x12!\n" +
	"\fsequence_len\x18\x03 \x01(\rR\vsequenceLen\x12\x1f\n" +
	"\vfeature_dim\x18\x04 \x01(\rR\n" +
	"featureDim\"v\n" +
	"\x11StreamLogsRequest\x12<\n" +
	"\tmin_level\x18\x01 \x01(\x0e2\x1f.signmind.inference.v1.LogLevelR\bminLevel\x12#\n" +
	"\rhistory_lines\x18\x02 \x01(\rR\fhistoryLines\"\x96\x01\n" +
	"\bLogEntry\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x125\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1f.signmind.inference.v1.LogLevelR\x05level\x12\x16\n" +
	"\x06logger\x18\x03 \x01(\tR\x06logger\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x12\n" +
	"\x10GetTuningRequest\"\xd4\x02\n" +
	"\x10SetTuningRequest\x126\n" +
	"\x14confidence_threshold\x18\x01 \x01(\x02H\x00R\x13confidenceThreshold\x88\x01\x01\x12?\n" +
	"\x1aidle_min_frames_with_hands\x18\x02 \x01(\rH\x01R\x16idleMinFramesWithHands\x88\x01\x01\x12>\n" +
	"\x19idle_motion_std_threshold\x18\x03 \x01(\x02H\x02R\x16idleMotionStdThreshold\x88\x01\x01\x12\"\n" +
	"\n" +
	"debug_mode\x18\x04 \x01(\bH\x03R\tdebugMode\x88\x01\x01B\x17\n" +
	"\x15_confidence_thresholdB\x1d\n" +
	"\x1b_idle_min_frames_with_handsB\x1c\n" +
	"\x1a_idle_motion_std_thresholdB\r\n" +
	"\v_debug_mode\"\xde\x02\n" +
	"\vTuningState\x121\n" +
	"\x14confidence_threshold\x18\x01 \x01(\x02R\x13confidenceThreshold\x12:\n" +
	"\x1aidle_min_frames_with_hands\x18\x02 \x01(\rR\x16idleMinFramesWithHands\x129\n" +
	"\x19idle_motion_std_threshold\x18\x03 \x01(\x02R\x16idleMotionStdThreshold\x12!\n" +
	"\fmodel_loaded\x18\x04 \x01(\bR\vmodelLoaded\x12\x1f\n" +
	"\vnum_classes\x18\x05 \x01(\rR\n" +
	"numClasses\x12!\n" +
	"\fsequence_len\x18\x06 \x01(\rR\vsequenceLen\x12\x1f\n" +
	"\vfeature_dim\x18\a \x01(\rR\n" +
	"featureDim\x12\x1d\n" +
	"\n" +
	"debug_mode\x18\b \x01(\bR\tdebugMode*{\n" +
	"\bFileKind\x12\x19\n" +
	"\x15FILE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FILE_KIND_TFLITE_MODEL\x10\x01\x12\x17\n" +
	"\x13FILE_KIND_LABEL_MAP\x10\x02\x12\x1f\n" +
	"\x1bFILE_KIND_PREPROCESS_CONFIG\x10\x03*z\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x15\n" +
	"\x11LOG_LEVEL_WARNING\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\xe5\x03\n" +
	"\fTslInference\x12^\n" +
	"\x0fStreamInference\x12$.signmind.inference.v1.LandmarkFrame\x1a!.signmind.inference.v1.Prediction(\x010\x01\x12f\n" +
	"\vUploadModel\x12).signmind.inference.v1.UploadModelRequest\x1a*.signmind.inference.v1.UploadModelResponse(\x01\x12Y\n" +
	"\n" +
	"StreamLogs\x12(.signmind.inference.v1.StreamLogsRequest\x1a\x1f.signmind.inference.v1.LogEntry0\x01\x12X\n" +
	"\tGetTuning\x12'.signmind.inference.v1.GetTuningRequest\x1a\".signmind.inference.v1.TuningState\x12X\n" +
	"\tSetTuning\x12'.signmind.inference.v1.SetTuningRequest\x1a\".signmind.inference.v1.TuningStateB4Z2gitea.harumi.dev/Harumi/NSC/backend/internal/pb;pbb\x06proto3"

var (
	file_tsl_inference_proto_rawDescOnce sync.Once
	file_tsl_inference_proto_rawDescData []byte
)

func file_tsl_inference_proto_rawDescGZIP() []byte {
	file_tsl_inference_proto_rawDescOnce.Do(func() {
		file_tsl_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsl_inference_proto_rawDesc), len(file_tsl_inference_proto_rawDesc)))
	})
	return file_tsl_inference_proto_rawDescData
}

var file_tsl_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tsl_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tsl_inference_proto_goTypes = []any{
	(FileKind)(0),               // 0: signmind.inference.v1.FileKind
	(LogLevel)(0),               // 1: signmind.inference.v1.LogLevel
	(*LandmarkFrame)(nil),       // 2: signmind.inference.v1.LandmarkFrame
	(*Prediction)(nil),          // 3: signmind.inference.v1.Prediction
	(*ClassProb)(nil),           // 4: signmind.inference.v1.ClassProb
	(*FileHeader)(nil),          // 5: signmind.inference.v1.FileHeader
	(*UploadModelRequest)(nil),  // 6: signmind.inference.v1.UploadModelRequest
	(*UploadModelResponse)(nil), // 7: signmind.inference.v1.UploadModelResponse
	(*StreamLogsRequest)(nil),   // 8: signmind.inference.v1.StreamLogsRequest
	(*LogEntry)(nil),            // 9: signmind.inference.v1.LogEntry
	(*GetTuningRequest)(nil),    // 10: signmind.inference.v1.GetTuningRequest
	(*SetTuningRequest)(nil),    // 11: signmind.inference.v1.SetTuningRequest
	(*TuningState)(nil),         // 12: signmind.inference.v1.TuningState
}
var file_tsl_inference_proto_depIdxs = []int32{
	4,  // 0: signmind.inference.v1.Prediction.top:type_name -> signmind.inference.v1.ClassProb
	0,  // 1: signmind.inference.v1.FileHeader.kind:type_name -> signmind.inference.v1.FileKind
	5,  // 2: signmind.inference.v1.UploadModelRequest.header:type_name -> signmind.inference.v1.FileHeader
	1,  // 3: signmind.inference.v1.StreamLogsRequest.min_level:type_name -> signmind.inference.v1.LogLevel
	1,  // 4: signmind.inference.v1.LogEntry.level:type_name -> signmind.inference.v1.LogLevel
	2,  // 5: signmind.inference.v1.TslInference.StreamInference:input_type -> signmind.inference.v1.LandmarkFrame
	6,  // 6: signmind.inference.v1.TslInference.UploadModel:input_type -> signmind.inference.v1.UploadModelRequest
	8,  // 7: signmind.inference.v1.TslInference.StreamLogs:input_type -> signmind.inference.v1.StreamLogsRequest
	10, // 8: signmind.inference.v1.TslInference.GetTuning:input_type -> signmind.inference.v1.GetTuningRequest
	11, // 9: signmind.inference.v1.TslInference.SetTuning:input_type -> signmind.inference.v1.SetTuningRequest
	3,  // 10: signmind.inference.v1.TslInference.StreamInference:output_type -> signmind.inference.v1.Prediction
	7,  // 11: signmind.inference.v1.TslInference.UploadModel:output_type -> signmind.inference.v1.UploadModelResponse
	9,  // 12: signmind.inference.v1.TslInference.StreamLogs:output_type -> signmind.inference.v1.LogEntry
	12, // 13: signmind.inference.v1.TslInference.GetTuning:output_type -> signmind.inference.v1.TuningState
	12, // 14: signmind.inference.v1.TslInference.SetTuning:output_type -> signmind.inference.v1.TuningState
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tsl_inference_proto_init() }
func file_tsl_inference_proto_init() {
	if File_tsl_inference_proto != nil {
		return
	}
	file_tsl_inference_proto_msgTypes[4].OneofWrappers = []any{
		(*UploadModelRequest_Header)(nil),
		(*UploadModelRequest_Chunk)(nil),
	}
	file_tsl_inference_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsl_inference_proto_rawDesc), len(file_tsl_inference_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsl_inference_proto_goTypes,
		DependencyIndexes: file_tsl_inference_proto_depIdxs,
		EnumInfos:         file_tsl_inference_proto_enumTypes,
		MessageInfos:      file_tsl_inference_proto_msgTypes,
	}.Build()
	File_tsl_inference_proto = out.File
	file_tsl_inference_proto_goTypes = nil
	file_tsl_inference_proto_depIdxs = nil
}
