# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tsl_inference_pb2 as tsl__inference__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tsl_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TslInferenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInference = channel.stream_stream(
                '/signmind.inference.v1.TslInference/StreamInference',
                request_serializer=tsl__inference__pb2.LandmarkFrame.SerializeToString,
                response_deserializer=tsl__inference__pb2.Prediction.FromString,
                _registered_method=True)
        self.UploadModel = channel.stream_unary(
                '/signmind.inference.v1.TslInference/UploadModel',
                request_serializer=tsl__inference__pb2.UploadModelRequest.SerializeToString,
                response_deserializer=tsl__inference__pb2.UploadModelResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/signmind.inference.v1.TslInference/StreamLogs',
                request_serializer=tsl__inference__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=tsl__inference__pb2.LogEntry.FromString,
                _registered_method=True)
        self.GetTuning = channel.unary_unary(
                '/signmind.inference.v1.TslInference/GetTuning',
                request_serializer=tsl__inference__pb2.GetTuningRequest.SerializeToString,
                response_deserializer=tsl__inference__pb2.TuningState.FromString,
                _registered_method=True)
        self.SetTuning = channel.unary_unary(
                '/signmind.inference.v1.TslInference/SetTuning',
                request_serializer=tsl__inference__pb2.SetTuningRequest.SerializeToString,
                response_deserializer=tsl__inference__pb2.TuningState.FromString,
                _registered_method=True)


class TslInferenceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamInference(self, request_iterator, context):
        """Client (backend) streams landmark frames; server (Python) streams
        predictions whenever its 30-frame sliding window is full.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request_iterator, context):
        """Atomically replace the LSTM model and its companion files. The client
        streams, per file, one FileHeader followed by that file's chunks; the
        model file and label map are both required in a single call (preprocess
        config optional). The server validates the staged files (interpreter
        loads, label map parses) before hot-swapping; on any failure the
        previously loaded model stays live and the RPC returns an error status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Server streams its log records to the gateway: first up to
        `history_lines` buffered entries, then live entries until the client
        cancels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTuning(self, request, context):
        """Read / adjust runtime inference tuning (thresholds). SetTuning applies
        only the fields present in the request and returns the full resulting
        state. Values are runtime-only: they reset to preprocess_config.json
        defaults on service restart.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTuning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TslInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInference': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=tsl__inference__pb2.LandmarkFrame.FromString,
                    response_serializer=tsl__inference__pb2.Prediction.SerializeToString,
            ),
            'UploadModel': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=tsl__inference__pb2.UploadModelRequest.FromString,
                    response_serializer=tsl__inference__pb2.UploadModelResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=tsl__inference__pb2.StreamLogsRequest.FromString,
                    response_serializer=tsl__inference__pb2.LogEntry.SerializeToString,
            ),
            'GetTuning': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTuning,
                    request_deserializer=tsl__inference__pb2.GetTuningRequest.FromString,
                    response_serializer=tsl__inference__pb2.TuningState.SerializeToString,
            ),
            'SetTuning': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTuning,
                    request_deserializer=tsl__inference__pb2.SetTuningRequest.FromString,
                    response_serializer=tsl__inference__pb2.TuningState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signmind.inference.v1.TslInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('signmind.inference.v1.TslInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TslInference:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/signmind.inference.v1.TslInference/StreamInference',
            tsl__inference__pb2.LandmarkFrame.SerializeToString,
            tsl__inference__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/signmind.inference.v1.TslInference/UploadModel',
            tsl__inference__pb2.UploadModelRequest.SerializeToString,
            tsl__inference__pb2.UploadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/signmind.inference.v1.TslInference/StreamLogs',
            tsl__inference__pb2.StreamLogsRequest.SerializeToString,
            tsl__inference__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTuning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signmind.inference.v1.TslInference/GetTuning',
            tsl__inference__pb2.GetTuningRequest.SerializeToString,
            tsl__inference__pb2.TuningState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTuning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signmind.inference.v1.TslInference/SetTuning',
            tsl__inference__pb2.SetTuningRequest.SerializeToString,
            tsl__inference__pb2.TuningState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
